include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/ffi/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - flutter/
  errors:
    sdk_version_since: ignore
    invalid_annotation_target: ignore
    deprecated_member_use_from_same_package: ignore
